### ISSUE TITLE
querySelectorAll is not supported in IE<8

### ISSUE THREAD

**Issue by lagartoflojo** [borismus/device.js#3]
Very nice lib, thanks!

I did encounter the problem that document.querySelectorAll does not exist in IE versions before IE8, thus it throws an error. Since basically I don't care about redirecting a browser that doesn't support this, I wrapped the entire code in `if(document.querySelectorAll){ ... }`

**Comment by borismus** [comment]
Lack of `querySelectorAll` sounds like an error to me! Working as intended :)

More seriously though, I'm reluctant to include special cases and a polyfill for this, since I really don't care about IE<8. Updated readme to this effect.

**Comment by lagartoflojo** [comment]
Hi,
Well, I don't really want device.js to work on IE8, since it's obviously not mobile and it shouldn't redirect anyway. It's just a matter of not showing a JS error to those users.
