### ISSUE TITLE
Inclusion of Modernizr suggests that their copyright and permission notice should be included somewhere

### ISSUE THREAD

**Issue by Trott** [borismus/device.js#5]
Modernizr is released under dual BSD/MIT license.  Since a substantial chunk of Modernizr code is included here, the copyright and permission should be included with the project.  (Or maybe I've just been working in a library for too long.)

**Comment by paulirish** [comment]
This attribution meets my needs:
https://github.com/borismus/device.js/blob/master/build/device.js#L32
