### ISSUE TITLE
Info about SEO and different devices/media queries from Google?

### ISSUE THREAD

**Issue by lechup** [borismus/device.js#6]
Is there any Google Advice / Best practise (like here about multilanguage content: http://support.google.com/webmasters/bin/topic.py?hl=en&topic=2370587&parent=2371375&ctx=topic ), but devoted to 'multidevice' topic? I'm really interested how to say Google "Here is my content, but i also have optimized one for mobile, tablets and others X-width devices".

Putting content just like that on m.foo.com or tablet.foo.com won't be treated as a duplicate?

PS: I know it is not an issue, but You can always mention it in Your readme file. Somewhere near: "You may also want to distinguish between these different versions by providing separate URLs (eg. tablet.foo.com, m.foo.com and foo.com) for clarity and perhaps for SEO reasons."

**Comment by borismus** [comment]
Hopefully we will have something official on this topic soon, and when we do I'll be sure to link to it!

**Comment by lechup** [comment]
Ok, I hope You won't forget about link. Thanks for the reply!

PS: I want to connect Your device.js with Twitter bootstrap ( http://twitter.github.com/bootstrap/scaffolding.html#responsive ) + multidomain or preferably URL parameter (different templates / code base). Without strict guidelines from Google it doesn't make sense to start any change in the code...

**Comment by borismus** [comment]
Released yesterday: https://developers.google.com/webmasters/smartphone-sites/details Enjoy!
