### ISSUE TITLE
modernizr already has matchMedia polyfill

### ISSUE THREAD

**Issue by ryanseddon** [borismus/device.js#7]
Noticed that you include the polyfill for matchMedia as well as modernizr in your repo. If you check `mq` in the build it includes the polyfill under `Modernizr.mq` with a few more edge cases fixed. Also you won't double up on the injection method and you'll save some bytes!

http://modernizr.com/download/#-touch-mq-teststyles-prefixes

**Comment by borismus** [comment]
Thanks, fixed.
